GET http://localhost:3000/

### Get all jobs paginated
GET http://localhost:3000/api/jobs?page=0

### Get a job by id
GET http://localhost:3000/api/jobs/3

### Create new Job

POST http://localhost:3000/api/jobs
content-type: application/json

{
  "email": "user24@mail.com",
  "name": "Full Stack Developer (m/w/d)",
  "office": "Philippines",
  "subcompany": "NotACompany",
  "job_descriptions": {
    "jobDescription": [
      {
        "name": "Timezone"
      },
      {
        "value": "GMT+8"
      }
    ]
  }
}

### Approve job post
GET http://localhost:3000/api/mods/approve/3?authKey=ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnRiMlJKWkNJNk15d2lhbTlpU1dRaU9qTXNJbWxoZENJNk1UY3dOekk0T0RBME1Dd2laWGh3SWpveE56QTNORFl3T0RRd2ZRLnVCS1o1dFZ6UE5hRkxvMVlpVjhpakN2cHQ5bHhFTjVHMV8tNENUblEwU0k=

### Mark a job post as spam
GET http://localhost:3000/api/mods/mark-as-spam/3?authKey=ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnRiMlJKWkNJNk15d2lhbTlpU1dRaU9qTXNJbWxoZENJNk1UY3dOekk0T0RBME1Dd2laWGh3SWpveE56QTNORFl3T0RRd2ZRLnVCS1o1dFZ6UE5hRkxvMVlpVjhpakN2cHQ5bHhFTjVHMV8tNENUblEwU0k=
