

### Get all jobs paginated
GET https://jobboard-production-2cf3.up.railway.app/api/jobs?page=0

### Get a job by id
GET https://jobboard-production-2cf3.up.railway.app/api/jobs/6

### Create new Job

POST https://jobboard-production-2cf3.up.railway.app/api/jobs
content-type: application/json

{
  "email": "user18@mail.com",
  "name": "Senior Backend Developer (m/w/d)",
  "office": "Germany"
}

### Approve job post
GET http://localhost:3000/api/mods/approve/3?authKey=ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnRiMlJKWkNJNk15d2lhbTlpU1dRaU9qTXNJbWxoZENJNk1UY3dOekk0T0RBME1Dd2laWGh3SWpveE56QTNORFl3T0RRd2ZRLnVCS1o1dFZ6UE5hRkxvMVlpVjhpakN2cHQ5bHhFTjVHMV8tNENUblEwU0k=

### Mark a job post as spam
GET http://localhost:3000/api/mods/mark-as-spam/3?authKey=ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnRiMlJKWkNJNk15d2lhbTlpU1dRaU9qTXNJbWxoZENJNk1UY3dOekk0T0RBME1Dd2laWGh3SWpveE56QTNORFl3T0RRd2ZRLnVCS1o1dFZ6UE5hRkxvMVlpVjhpakN2cHQ5bHhFTjVHMV8tNENUblEwU0k=
